### ISSUE TITLE
Hide undo/redo buttons

### ISSUE THREAD

**Issue by drkane** [ccmdesign/360-insights#1]
Plotly annoying adds default undo/redo buttons to the dash tool.

The only way to remove them is through CSS - so can we add the following somewhere in the CSS:

```
._dash-undo-redo {
  display: none;
}
```

I wasn't sure of the best file to put them in.

**Comment by claudioccm** [comment]
@drkane - best way to do that is to create a sass partial to host all the "dash fixes". 
Ideally, the partial should be added as one of the first ones. before the components. 
Let me know if you have any problems with that.

**Comment by arthurbergmz** [comment]
Pull request accepted. #2
